In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

*'Since neural networks can only train on vectors, vectorizing data is a necessary pre-processing step.'*

"Deep Learning: A Practitioner's Approach" by Adam Gibson and Josh Patterson (O'Reily).

Casting neural networks as matrices and vectors enables one to utilize many of the properties of matrices and vectors to compactly handle computations.  Matrices and vectors are a very convenient way of representing neural networks.   

In [2]:
A = np.array([[1,2], [3,-4]])

In [3]:
A

array([[ 1,  2],
       [ 3, -4]])

In [4]:
np.identity(A.ndim)

array([[1., 0.],
       [0., 1.]])

In [5]:
from numpy import linalg as LA

In [6]:
Eigenvalues, Eigenvectors = LA.eig(np.array([[1, 2], [3, -4]]))

In [7]:
Eigenvalues

array([ 2., -5.])

In [9]:
Eigenvectors

array([[ 0.89442719, -0.31622777],
       [ 0.4472136 ,  0.9486833 ]])

20190128_162149first.jpg![](20190128_162149first.jpg)

![](20190128_163200middle.jpg)

![](20190128_163556last.jpg)

**Conclustion:** Matrices and vectors play an essential role in neural networks.  Vectors and matrices help by compressing all the calculations into very simple notations and their operations are fast and easy, especially when training on GPUs.  Matrix multiplication is one of the most important operations in deep learning.

<font color = green, font size = 11 >**Appendix**</font>

**What is a GPU?**  GPU (Graphics processing unit) - a specialized electronic circuit designed to rapidly manipulate and alter memory to accelerate the creation of images in a frame buffer intended for output to a display device. GPUs are used in embedded systems, mobile phones, personal computers, workstations, and game consoles.

**Great learning resource for linear algebra:**
    
https://www.youtube.com/results?search_query=3blue1brown+linear+algebra

**What is a matrix?**

A matrix is an m × n array of scalars from a given field.  The individual values in the matrix are called entries.

![Example:](Screenshot from 2019-01-29 09-43-51.png)

**What is a vector?** 

Vectors are lists of numbers. In a geometric sense, a vector is where each number represents coordinates relative to some axes. Vectors are also described as just coordinates on the plane.  For example, [1,1] is a vector pointing up and to the right from the origin to the coordinate (1,1).  Vectors can also be seen as geometric transformations of the plane such as rotating, squashing, shearing or stretching.

**What is an eigenvector?**  An eigenvector of a linear transformation is a non-zero vector that changes by only a scalar factor when that linear transformation is applied to it. 

**What is an eigenvalue?**  An eigenvalue is a set of values of a parameter for which a differential equation has a nonzero solution (an eigenfunction) under given conditions.  An eigenvalue is also any number such that a given matrix minus that number times the identity matrix has zero determinant.

![](Screenshot from 2019-01-29 09-59-28.png)


![](https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Eigenvalue_equation.svg/250px-
Eigenvalue_equation.svg.png)

Matrix A acts by stretching the vector x, not changing its direction, so x is an eigenvector of A.

**Eigenvalues of geometric transformations** - The following table presents some example transformations in the plane along with their 2×2 matrices, eigenvalues, and eigenvectors.

![](Screenshot from 2019-01-29 10-04-33.png)

**Homework practice**

http://math.colgate.edu/~wweckesser/math312Spring06/handouts/IMM_2x2linalg.pdf