![](https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Eigenvalue_equation.svg/250px-Eigenvalue_equation.svg.png)

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')
from scipy.spatial.distance import cdist
from sklearn.cluster import KMeans

In [2]:
A = np.array([[1,2], [3,-4]])

In [3]:
A

array([[ 1,  2],
       [ 3, -4]])

In [4]:
np.identity(A.ndim)

array([[1., 0.],
       [0., 1.]])

In [5]:
from numpy import linalg as LA

In [6]:
Eigenvalues, Eigenvectors = LA.eig(np.array([[1, 2], [3, -4]]))

In [7]:
Eigenvalues

array([ 2., -5.])

In [8]:
(A * Eigenvectors [:,1])/Eigenvectors[:,1]

array([[ 1.,  2.],
       [ 3., -4.]])

In [9]:
Eigenvectors

array([[ 0.89442719, -0.31622777],
       [ 0.4472136 ,  0.9486833 ]])

20190128_162149first.jpg![](20190128_162149first.jpg)

![](20190128_163200middle.jpg)

![](20190128_163556last.jpg)